# Generated by Django 4.1.3 on 2022-11-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('ville', models.CharField(max_length=1024, null=True)),
                ('latitude', models.FloatField(max_length=120, null=True)),
                ('longitude', models.FloatField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=50)),
                ('jobImageUrl', models.FileField(blank=True, null=True, upload_to='csv_files', verbose_name='CSV File')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobCategoryName', models.CharField(max_length=50)),
                ('jobCategoryImageUrl', models.FileField(blank=True, null=True, upload_to='csv_files', verbose_name='CSV File')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=3000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('photoUrl', models.ImageField(blank=True, null=True, upload_to='csv_files', verbose_name='CSV File')),
                ('displayName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('aboutMe', models.CharField(max_length=300, null=True)),
                ('isWorker', models.BooleanField(verbose_name='IsWorker')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshopName', models.CharField(max_length=50)),
                ('workshopImageUrl', models.FileField(blank=True, null=True, upload_to='csv_files', verbose_name='CSV File')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='core.address')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='core.job')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workerMember', to='core.member')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='core.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLikeMember', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postCommentText', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postCommentMember', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postText', models.TextField(blank=True, null=True)),
                ('postContentUrl', models.FileField(blank=True, null=True, upload_to='csv_files', verbose_name='CSV File')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('postcomments', models.ManyToManyField(blank=True, related_name='postComments', to='core.postcomment')),
                ('postlikes', models.ManyToManyField(blank=True, related_name='postLikes', to='core.postlike')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageContent', models.CharField(max_length=50)),
                ('messageFileUrl', models.FileField(blank=True, null=True, upload_to='csv_files', verbose_name='CSV File')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('memberFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberFrom', to='core.member')),
                ('memberTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberTo', to='core.member')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jobCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobCategory', to='core.jobcategory'),
        ),
    ]
