# Generated by Django 4.1.2 on 2022-10-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_post_comments_post_postcomments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobCategoryName', models.CharField(max_length=50)),
                ('jobCategoryImageUrl', models.FileField(blank=True, null=True, upload_to='csv_files', verbose_name='CSV File')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=50)),
                ('jobImageUrl', models.FileField(blank=True, null=True, upload_to='csv_files', verbose_name='CSV File')),
                ('jobCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobCategory', to='core.jobcategory')),
            ],
        ),
    ]
